topic/posts/urls.py
"""Posts URLs"""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [

        # Posts
    
    path(
        route='posts/<str:post_id>/',
        view=views.PostDetailView.as_view(),
        name='post_detail'
    ),

    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed',
    ),

    path(
        route='post/new/',
        view=views.CreatePostView.as_view(),
        name='create',
    )
]

topic/topic/urls.py
""" Topic url's module"""

#django
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings





urlpatterns = [
    path('admin/',admin.site.urls),

    path('', include(('posts.urls', 'posts'),namespace='posts')),
        
    path('users/', include(('users.urls','users'), namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

topic/users/urls.py
"""Users URLs"""
# Django
from django.urls import path


# View
from users import views

urlpatterns = [

    # Posts
    path(
        route='@<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    #management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='me/profile/',
        view=views.ProfileUpdateView.as_view(),
        name='update_profile'
    )
]

topic/posts/models.py
"""Posts models here"""

#django imports

from django.db import models
from django.contrib.auth.models import User




class Post(models.Model):
    """ Post model"""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)
    
    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/photos')

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

def __str__(self):
    """Return title and username"""

    return f'{self.title} by  @{self.user.username}'

topic/users/models.py
""" Users models."""

#django
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Profile(models.Model):
    """proxy model that extense the base data other information"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20,blank=True)

    picture = models.ImageField(upload_to='users/pictures', blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def __str__(self):

        """Return username"""
        return self.user.username

topic/posts/forms.py
"""Post forms"""

#django 
from django import forms

#models
from posts.models import Post

class PostForm (forms.ModelForm):
    """Post model form."""
    class Meta:
        """Form settings"""
        model = Post
        fields = ['user','Profile','title','photo']

topic/users/forms.py
""" User Form """
#django
from django import forms
from django.contrib.auth.models import User

#models
from users.models import Profile

class signupForm(forms.Form):
    """sign up form"""
    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )

    confirmation_password = forms.CharField(
        max_length= 70,
        widget= forms.PasswordInput()
    )

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length= 6,
        max_length= 70,
        widget = forms.EmailInput()
    )
    def clean_username(self):
        """"Username must be unique"""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()

        print(username,'vs',username_taken)

        if username_taken:
            raise forms.ValidationError('Username is already in use. ')
        return username
    
    def clean(self):
        """Verify password confirmation match"""
        data= super().clean()

        password = data['password']
        confirmation_password = data['confirmation_password']

        if password != confirmation_password:
            raise forms.ValidationError('Passwords do not match')
        
        return data

    def save(self):
        """Create and save user and profile"""
        data = self.cleaned_data
        data.pop('confirmation_password')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()


    

class ProfileForm(forms.Form):
    website = forms.URLField(max_length=200, required = True)
    biography = forms.CharField(max_length=500,required=False)
    phone_number = forms.CharField (max_length=20, required=False)
    picture = forms.ImageField()

topic/posts/views.py
"""Posts views"""

#django
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView

#forms
from posts.forms import PostForm

#models
from posts.models import Post



class PostsFeedView(LoginRequiredMixin, ListView):
    """return all published posts"""

    template_name = 'posts/feed.html'
    model = Post
    ordering = ('-created')
    paginate_by = 3
    context_object_name= 'posts'

class PostDetailView(LoginRequiredMixin,DetailView):
    """User detail view."""
	
    template_name='posts/detail_post.html'
    slug_field= 'id'
    slug_url_kwarg='post_id'
    queryset = Post.objects.all()

    context_object_name = 'post'

class CreatePostView(LoginRequiredMixin,CreateView):
    """Create a new post"""
    template_name= 'posts/new.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:feed')
    


    def get_context_data (self, **kwargs):
        """Add user and profile to context"""

        context= super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['Profile']= self.request.user.profile

        return context

topic/users/views.py
"""users view"""
#django 

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse,reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth import views as auth_views



#models 
from posts.models import Post
from users.models import User, Profile

#forms 
from users.forms import  signupForm

class UserDetailView(LoginRequiredMixin,DetailView):
    """User detail view."""
	
    template_name='users/detail.html'
    slug_field= 'username'
    slug_url_kwarg='username'
    queryset = User.objects.all()

    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context"""

        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')

        return context

class LoginView(auth_views.LoginView):
    """Login user view"""
    
    template_name = 'users/login.html'

class LogoutView(LoginRequiredMixin,auth_views.LogoutView):
    """Users Logout view"""
    next_page= 'users:login'


class SignupView(FormView):
    """user signup view"""
    form_class = signupForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('users:login')
    
    def form_valid(self,form):
        """save form data"""
        form.save()

        return super().form_valid(form)

class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'users/update_profile.html'
    model= Profile
    fields = ['website','biography','phone_number','picture']
    

    def get_object(self):
        """return user´s profile"""
        return self.request.user.profile
    
    def get_success_url(self):
        """return to user's profile"""
        username=self.object.user.username
        return reverse('users:detail', kwargs={'username':username})

topic/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head_content %} {%endblock%}
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Questrial&display=swap');
        </style>

</head>
<body>
    {% include "nav.html" %}
    <div class="container pt-5">

        {% block container %}
        {% endblock%}

    </div>
</body>
</html>

topic/templates/footer.html
<div class="justify-content-center card-footer  text-center">
    <p>Gabo</p>
</div>

topic/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">
        <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarTogglerDemo02">
            
            <ul class="navbar-nav mr-auto d-flex flex-row">
                <li >
                    <a href="{% url 'users:detail' request.user.username%}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" class="rounded-circle mb-2 border border-4" height="50" />
                        {% else%}
                            <img src="{% static 'img/default-profile.png' %}" class="rounded-circle mb-2 border border-4" height="50" />
                        {% endif %}
                    </a>
                </li>
                <li class="mx-3 my-3">
                    <a  href="{% url 'posts:create' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>
            </ul>

            <ul class="navbar-nav mr-auto d-flex flex-column ">
                <li>
                    <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
                        <img src="{% static 'img/instagram.png' %}" height="45" class="d-inline-block align-top"/>
                    </a>
                </li>
                <li>
                    <a href="#" class="navbar-brand">
                        ToPic
                    </a>
                </li>
            </ul>

            <ul class="navbar-nav mr-auto ">

                    <li class="nav-item nav-icon">
                        <a href="{% url 'users:logout' %}">
                            <i class="fas fa-sign-out-alt"></i>
                        </a>
                    </li>

            </ul>
        </div>
        
    </div>
</nav>

topic/templates/posts/detail_post.html
{%extends "base.html" %}

{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile - ToPic</title>
{% endblock %}

{% block container %}

<div class="container pt-4">
    
    {% include "reusables/post_card.html" %}

</div>


{% endblock %}

topic/templates/posts/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>ToPic</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row pt-4">
            
            {% for post in posts %}
              {% include "reusables/post_card.html" %}
            {% endfor %}

            {%include "reusables/pagination.html"%}
        </div>
    </div>
    
{% endblock %}

topic/templates/posts/new.html
{% extends "base.html" %}

{% block head_content %}
<title>Create new post - ToPic</title>
{% endblock %}

{% block container %}

    <div class="container pt-5">
        <div class="row justify-content-md-center pt-4">
            <div class="col-6 py-4 px-4" id="profile-box">
                <h4 class="mb-4">Post a new photo!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="Profile" value="{{ user.profile.pk}}" />

                    {# title field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                            value="{% if form.errors %}{{form.title.value}}{% endif %}"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Choose your photo:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="photo"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

topic/templates/reusables/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

topic/templates/reusables/post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media p-3 d-flex flex-row justify-content-between">
        <a style="text-decoration: none; color: black;" href="{% url 'users:detail' post.user.get_username%}" >
            <img 
            class="mr-3 rounded-circle" 
            height="35" 
            src="{{ post.user.profile.picture.url }}" 
            alt="{{ post.user.get_full_name }}"
            ><b class="m-1">{{ post.user.get_full_name}}</b></a>
            <span class="me-3">
                {% if user.username == post.user.get_username %}
                <a href="{% url 'posts:post_detail' post.id %} ">
                    <class class="far fa-edit"></class>
                </a>
                {% else %}
                {% endif %}
            </span>
    </div>
   
        <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">
    <p class="pt-2 p-3 pb-1" >
        <a href="" class="link-secondary px-1">
            <i class="far fa-heart" ></i></a>
        30 likes
        
        <a href="" class="link-secondary px-1">
            <i class="far fa-comment-alt" ></i></a>
        x comments
    </p>
    <p class="pt-0 p-3 pb-1">
        <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
    </p>
</div>

topic/templates/reusables/user_profile.html
{% load static %}

<div class="container pt-5" >
    <div class="row px-3 pt-4">
        <div class="col col-xs-5 col-sm-4 col-md-4 col-lg-2">
            <img src="
            {% if not user.profile.picture %}
                {% static 'img/default-profile.png' %}
            {% else %}
                {{ user.profile.picture.url }}
            {% endif %}" 
            alt="@{{ user.username}}" 
            class="img-fluid rounded-circle mx-auto d-block" 
            style="min-width:130px; max-width: 130px;" />
        </div>

        <div class="col col-xs-7 col-sm-8 col-md-8 col-lg-10 ">
            <div class="w-50 mb-2 col-lg-6 col-xl-6">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                </h2>
            </div>
            <div class=" mb-2 col-lg-6 col-xl-6 ">
                {% if user == request.user %}
                <a
                    href="{% url 'users:update_profile' %}"
                    class="ml-5 btn btn-outline-info w-100"
                >
                    Edit profile
                </a>
            {% else %}
                <a
                    href=""
                    class="ml-5 btn btn-primary w-100"
                >
                    Follow
                </a>
            {% endif %}
            </div>
            <div class="d-flex flex-row justify-content-arround ">
                <div class="px-3">
                    <b>{{ user.profile.posts_count }}785</b> posts
                </div>
        
                <div class="px-3">
                    <b>{{ user.profile.followers }}1,401</b> followers
                </div>
                <div class="px-3">
                    <b>{{ user.profile.following }}491</b> following
                </div>
            </div>
        </div>

    </div>
            <div class="w-100 mt-4">
                <div class="col-sm-12">
                    <p>{{ user.profile.biography }}</p>
                </div>
            </div>

        </div>



    </div>
</div>

topic/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="d-flex flex-column justify-content-between h-100">
    
    <div class="container p-4">
        <div class="row justify-content-center">
            <div class=" col-sm-12 col-md-8 col-lg-5 col-xl-4 py-4 " id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>
    {% include 'footer.html' %}
</body>
</html>

topic/templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | ToPic</title>
{% endblock %}



{% block container %}

    {%include "reusables/user_profile.html"%}
    
    <div class="container " id="user-posts">
        <div class="row g-3 mt-2">
            {% for post in posts %}
            <div class="col-4 pt-5 pb-5 pr-4 pl-4 ">
                <a href="{% url 'posts:post_detail' post.id %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid mx-auto d-block"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    <hr>

{% endblock %}

topic/templates/users/login.html
{% extends "users/base.html" %}

 {% block head_content %}
    <title>ToPic login</title>
 {% endblock %}


 {% block container %}

    <div class="form-signin container px-5 py-1">
        
        {% if form.errors %}
            {% for key,error in form.errors.items %}    
            <p class="text-danger"> 
                *{% if key != '__all__' %}
                      {{key}}:
                    {% endif %}                        
                    {%for value in error%}
                      {{value}}
                    {% endfor %}
            </p>
            {%endfor%}
        {% endif %}

        <form action="{% url 'users:login'  %}" method="post">
            
            {% csrf_token %} <!--token for secure auntenticated -->

            <h1 class="h3 mb-3 fw-normal">Please Sign in!</h1>
            <div class="form-floating">
                <input class="form-control" type="text" placeholder="Username" name="username" />
                <label for="floatingInput">Username</label>
            </div>
            <div class="form-floating">
                <input class="form-control" type="password" placeholder="Password" name="password" />
                <label for="floatingInput">Password</label>
            </div>

            <div class="checkbox mb-3">
                <label>
                  <input type="checkbox" value="remember-me"> Remember me
                </label>
              </div>

              <input type="hidden" name="next" value="{%url 'posts:feed' %}">

        <button class="w-100 btn btn-lg btn-primary" type="submit">Sing in</button>
        
        </form>
        <p class="mt-4">
            Don't have an account yet? <a href="{% url 'users:signup' %}"> Sing up here.</a>
        </p>
    </div>


 {% endblock %}

topic/templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>ToPic signup</title>
{% endblock %}

{% block container  %}
    
    <main class="form-signin container ">

        {% if error %}
          <p class="alert alert-danger"> {{error}}</p>
        {% endif %}

        <form action="{% url 'users:signup'  %}" method="post">
            
            {% csrf_token %} <!--token for secure auntenticated -->

            {{ form.as_p }}

        <button class="w-100 btn btn-lg btn-primary" type="submit">Register</button>
        
        </form>
        <p class="mt-4">
            Already have an account? <a href="{% url 'users:login' %}"> Login here.</a>
        </p>
    </main>

{% endblock %}

topic/templates/users/update_profile.html
{% extends "base.html" %}

{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile - ToPic</title>
{% endblock %}

{% block container %}

<div class="container mt-5">
    
    <div class="row  justify-content-md-center pt-4">

      <div class="col col-lg-2 col-12">
        <div class="media ">
            {% if profile.picture %}
                <img src="{{ profile.picture.url }}" class="rounded-circle mb-2 border border-4" height="100" />
            {% else%}
                <img src="{% static 'img/default-profile.png' %}" class="rounded-circle mb-2 border border-4" height="100" />
            {% endif %}

            <div class="media-body">
                <h5 class="ml-4">@{{ user.username }}</h5> <p>{{ user.get_full_name }}</p>
            </div>
        </div>
      </div>
      
      <div class="col col-lg-8 col-12">
        <div class="col-8 p-4 ml-2 ms-0 w-100" id="profile-box">

            <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data" >
                {% csrf_token %}

                <h3 class="h3">Edit profile</h3>

                <hr>
                {# picture field #}
                <div class="form-group">
                    <label for="formFileSm" class="form-label ">Change profile photo</label>
                    <input class="form-control form-control-sm" type="file" name="picture" id="formFileSm">
                </div>
                <p class="text-danger fs-6 ">
                    {% for error in form.picture.errors %} 
                    <b>Picture:</b>{{error}}
                    {% endfor %}
                </p>

                {# website field #}
                <div class="form-group mb-2">
                    <label>Website</label>
                    <input
                        class="form-control {% if form.website.errors %}is-invalid{%endif%}"
                        type="text"
                        name="website"
                        placeholder="Website"
                        value="{% if form.website.errors %}{{form.website.value}}{% else %}{{profile.website}}{% endif %}"
                    />
                    <span class="invalid-feedback">
                      {% for error in form.website.errors %} 
                        {{error}}
                      {% endfor %}
                    </span>
                </div>
                
                {# Biography field #}
                <div class="form-group mb-2">
                    <label>Biography</label>
                    <textarea 
                    class="form-control 
                    {% if form.biography.errors %}
                      is-invalid
                    {%endif%}"
                    name="biography">{% if form.biography.errors %}{{form.biography.value}}{% else %}{{profile.biography}}{% endif %}</textarea>
                    <span class="invalid-feedback">
                      {% for error in form.biography.errors %} 
                        {{error}}
                      {% endfor %}
                    </span>
                </div>

                {# Phone number field #}
                <div class="form-group mb-2">
                    <label>Phone number</label>
                    <input
                        class="form-control 
                        {% if form.phone_number.errors %}
                          is-invalid
                        {%endif%}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.phone_number.errors %}{{form.phone_number.value}}{% else %}{{profile.phone_number}}{% endif %}"
                    />
                    <span class="invalid-feedback">
                      {% for error in form.phone_number.errors %} 
                        {{error}}
                      {% endfor %}
                    </span>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
      </div>
      <div class="col col-lg-2 col-12"></div>
    </div>
  </div>
    

{% endblock %}